#include <stdbool.h>
#include <stdint.h>

// ---- This header is automatically generated by Atom ----


void atom_tick();

extern struct {  /* state_example */
  struct {  /* atom_example */
    uint64_t clock_sec;
    struct {  /* check_sensor */
      uint64_t warmup;
      bool triggered;
      bool sensor_on;
    } check_sensor;
  } atom_example;
} state_example;


// ---- End automatically-generated header ----

